In [43]:
import pandas as pd
from pandas.plotting import radviz
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
#import the model we are using
from sklearn.ensemble import RandomForestRegressor
from sklearn import svm, preprocessing
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn import linear_model
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [44]:
def read(file):
    return pd.read_csv(file)

#features.set_index(['Index'], inplace = True)
#features.drop(columns = ['Index'], inplace = True)

features = read('csv_data.csv')
features.head(5)

H [mm]     Nγ [ ]  γAH' [N]   Pmax [N]
0    90.0   7.178479  1.264982   9.080644
1    90.0  13.881967  0.630942   8.758713
2    90.0   9.291625  1.264982  11.753734
3    90.0  17.113597  0.630942  10.797683
4    90.0  11.142517  1.264982  14.095079

In [45]:
def print_shape(data):
    print("The shape of our feature is " + str(data.shape))

print_shape(features)

The shape of our feature is (177, 4)


In [46]:
#summary statistics
features.describe()
features.columns.values

array(['H [mm]', 'Nγ [ ]', "γAH' [N]", 'Pmax [N]'], dtype=object)

In [47]:
#pd.options.display.max_rows = 181
pd.options.display.max_columns = 30
#features.sort_values(by = "L [mm]", ascending = True, inplace = True)
#display(features)

In [48]:
#one hot encoding
pd.options.display.max_columns = 181
pd.options.display.max_rows = 181
#features = pd.get_dummies(features, columns = ['n [count]', 'Material'])
#features = pd.get_dummies(features, columns = ['n [count]'])
#features = pd.get_dummies(features, columns = ['Material'])
#features.head(5)
#display(features)
#print_shape(features)

In [49]:


#target pmax
pmax = np.array(features['Pmax [N]'])
#Remove labels from the features
features = features.drop('Pmax [N]', axis = 1)

features = StandardScaler().fit_transform(features)

#pca = PCA(n_components = 11)
#principalComponents = pca.fit_transform(features)
#features = pd.DataFrame(data = principalComponents, columns = ['pc1', 'pc2','pc3','pc4','pc5','pc6','pc7','pc8','pc9','pc10','pc11'])
#display(features)
#print(pca.explained_variance_ratio_.cumsum())

#Covert to numpy arrays
features = np.array(features)



#print(features)
print_shape(features)

The shape of our feature is (177, 3)


In [50]:
#split the data into training set and testing set 
train_features, test_features, train_labels, test_labels = train_test_split(features, pmax, test_size = 0.25, random_state = 42)

In [51]:
print('Training Features Shape:', train_features.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_features.shape)
print('Testing Labels Shape:', test_labels.shape)

Training Features Shape: (132, 3)
Training Labels Shape: (132,)
Testing Features Shape: (45, 3)
Testing Labels Shape: (45,)


In [39]:
#Establish Baseline

In [40]:
#instantiate the model 
rf = RandomForestRegressor(n_estimators = 570, random_state = 141)
# n_estimator is lambda
# use cross validation to optimize the n_estimators 
# use k_fold
#change the n_estimator to discover the difference 
#SVM, SVR, knernel RBF, logistic regression, naive base (compare between gernerateive method and discrimitive method)
#ensemble method(random bagging)
#plot those regression
#PCA Get the result (visualize it)
# --> classfication using high value, mid value, low value
#train the model on training data

#cumulate the features to see the result
rf.fit(train_features, train_labels)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=570,
                      n_jobs=None, oob_score=False, random_state=141, verbose=0,
                      warm_start=False)

In [41]:
#Make Predictions
#Use the forest's predict method on the test data 
predictions = rf.predict(test_features)

#Calculate the absolute errors
errors = abs(predictions - test_labels)

#print out the mean absolute error
print('Mean Absolute Error:', round(np.mean(errors), 2), 'newton.')

Mean Absolute Error: 2.22 newton.


In [42]:
# Calculate mean absolute percentage error
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Accuracy: 89.17 %.


Kernel rbf

In [14]:
#kernel (rbf)
clf = svm.SVR(kernel = "rbf")
clf.fit(train_features,train_labels)
print(clf.score(train_features, train_labels))

0.4665054619980621


C:\Users\fmh\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [15]:

errors = 0
for X,y in zip(test_features, test_labels):
    print(f"Model: {clf.predict([X])[0]}, Actual: {y}")
    errors += abs(clf.predict([X])[0] - y)
errors = errors / test_features.shape[0]

print('Mean Absolute error:',round(errors, 2) , 'newton.')

# Calculate mean absolute percentage error
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')



Model: 18.040228219492604, Actual: 16.465722631585038
Model: 11.095639681647604, Actual: 10.497081539108782
Model: 10.801689560088914, Actual: 9.639485549900499
Model: 35.61397747348366, Actual: 42.357748607195
Model: 25.059185170873768, Actual: 6.063413449065
Model: 27.898925757716846, Actual: 26.367723489059344
Model: 10.339948922841511, Actual: 7.934872992134268
Model: 35.59027603426565, Actual: 51.879055492810004
Model: 10.479885484487934, Actual: 7.861187715016644
Model: 19.111841338832345, Actual: 13.370124772445
Model: 22.559623470964713, Actual: 14.934077561135252
Model: 18.865747123387155, Actual: 20.180180267904998
Model: 15.311939727218618, Actual: 21.948365576357837
Model: 10.243736515596854, Actual: 5.702605711267501
Model: 14.847698355318393, Actual: 13.890200587874556
Model: 19.40223430309346, Actual: 15.198136307690001
Model: 13.377283971512044, Actual: 13.187881911505
Model: 20.135902376802868, Actual: 23.019568288954996
Model: 12.85757301117515, Actual: 12.05044388194

kernel polynomial

In [16]:
clf = svm.SVR(kernel = "poly")
clf.fit(train_features,train_labels)
print(clf.score(train_features, train_labels))

0.7144429886496988


C:\Users\fmh\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [17]:
errors = 0
for X,y in zip(test_features, test_labels):
    print(f"Model: {clf.predict([X])[0]}, Actual: {y}")
    errors += abs(clf.predict([X])[0] - y)
errors = errors / test_features.shape[0]

print('Mean Absolute error:',round(errors, 2) , 'newton.')

# Calculate mean absolute percentage error
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Model: 17.717995436621145, Actual: 16.465722631585038
Model: 15.604561106027115, Actual: 10.497081539108782
Model: 15.3339887289113, Actual: 9.639485549900499
Model: 31.487924386666393, Actual: 42.357748607195
Model: 5.115343081762523, Actual: 6.063413449065
Model: 18.42027356687719, Actual: 26.367723489059344
Model: 14.814340843699885, Actual: 7.934872992134268
Model: 59.316703783256216, Actual: 51.879055492810004
Model: 14.385114909757823, Actual: 7.861187715016644
Model: 14.078629557261168, Actual: 13.370124772445
Model: 16.07333421489387, Actual: 14.934077561135252
Model: 17.835385961009585, Actual: 20.180180267904998
Model: 17.056073157966157, Actual: 21.948365576357837
Model: 13.36390506213278, Actual: 5.702605711267501
Model: 17.158040798331726, Actual: 13.890200587874556
Model: 14.500932508324624, Actual: 15.198136307690001
Model: 15.685842193387566, Actual: 13.187881911505
Model: 17.819787778108935, Actual: 23.019568288954996
Model: 16.57064583724614, Actual: 12.05044388194499

Linear

In [18]:
clf = svm.SVR(kernel = "linear")
clf.fit(train_features,train_labels)
print(clf.score(train_features, train_labels))

0.7828080637914053


In [19]:
errors = 0
for X,y in zip(test_features, test_labels):
    print(f"Model: {clf.predict([X])[0]}, Actual: {y}")
    errors += abs(clf.predict([X])[0] - y)
errors = errors / test_features.shape[0]

print('Mean Absolute error:',round(errors, 2) , 'newton.')

# Calculate mean absolute percentage error
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Model: 18.065056240711648, Actual: 16.465722631585038
Model: 10.386270272615969, Actual: 10.497081539108782
Model: 9.686581855686237, Actual: 9.639485549900499
Model: 42.01362245869215, Actual: 42.357748607195
Model: 15.361720145493832, Actual: 6.063413449065
Model: 29.076046485466982, Actual: 26.367723489059344
Model: 8.408376673010174, Actual: 7.934872992134268
Model: 61.168195572375126, Actual: 51.879055492810004
Model: 7.672538873496094, Actual: 7.861187715016644
Model: 11.551206528443776, Actual: 13.370124772445
Model: 19.476259891868537, Actual: 14.934077561135252
Model: 20.30843781155342, Actual: 20.180180267904998
Model: 16.59606306818967, Actual: 21.948365576357837
Model: 5.665215737620521, Actual: 5.702605711267501
Model: 15.071756302479823, Actual: 13.890200587874556
Model: 12.292082708143377, Actual: 15.198136307690001
Model: 11.612196881339443, Actual: 13.187881911505
Model: 22.05850643175863, Actual: 23.019568288954996
Model: 12.933570901322536, Actual: 12.050443881944997

Linear Regression

In [20]:
reg = linear_model.LinearRegression()
reg.fit(train_features, train_labels)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [21]:
reg.coef_

array([10.82724113,  8.95380538,  7.68126298])

In [22]:
a = reg.predict(test_features)

In [23]:
a

array([17.81624191,  9.6736562 ,  9.01689806, 50.9063613 ,  3.67322262,
       33.4259413 ,  7.9039828 , 65.79538434,  6.86736681,  6.59287955,
       14.2223678 , 22.19989041, 14.66009242,  5.06466743, 14.71801955,
        7.21490775,  9.57671007, 24.10748199, 12.50488557, 29.97028518,
       54.59100978, 16.34027799, 39.43071564, 38.52239321, 50.90143481,
       11.20286626, 54.10558053, 16.35995792, 54.25435877, 17.27093509,
       31.71885885,  8.42707815, 23.55534062, -2.46630734, 47.49425767,
       18.35718133, 33.31628634,  5.52408083,  8.94454976, 28.26423832,
       54.45455284, 11.26412936, 36.70758888, -3.52696574, 28.93506662])

In [24]:
test_labels

array([16.46572263, 10.49708154,  9.63948555, 42.35774861,  6.06341345,
       26.36772349,  7.93487299, 51.87905549,  7.86118772, 13.37012477,
       14.93407756, 20.18018027, 21.94836558,  5.70260571, 13.89020059,
       15.19813631, 13.18788191, 23.01956829, 12.05044388, 30.12463135,
       46.46724392, 17.4608159 , 36.43282565, 42.2909006 , 50.76684115,
       12.18658186, 52.19937304, 17.48030047, 66.92157596, 17.61683835,
       25.43328788, 11.12583075, 17.90312419,  6.78808322, 35.8835797 ,
       18.01685272, 36.44491235,  6.40484236,  8.74897018, 29.22451131,
       47.88742336, 11.52937088, 36.89477084,  9.90338574, 25.34278329])

In [25]:
np.mean(abs(test_labels - a))
print('Mean Absolute error:',round(errors, 2) , 'newton.')

Mean Absolute error: 2.65 newton.


In [26]:
# Calculate mean absolute percentage error
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Accuracy: 82.64 %.


logistic regression


In [27]:
clf = svm.SVR(kernel = "sigmoid")
clf.fit(train_features,train_labels)
print(clf.score(train_features, train_labels))

0.634815389161655


C:\Users\fmh\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [28]:
errors = 0
for X,y in zip(test_features, test_labels):
    print(f"Model: {clf.predict([X])[0]}, Actual: {y}")
    errors += abs(clf.predict([X])[0] - y)
errors = errors / test_features.shape[0]

print('Mean Absolute error:',round(errors, 2) , 'newton.')

# Calculate mean absolute percentage error
mape = 100 * (errors / test_labels)

# Calculate and display accuracy
accuracy = 100 - np.mean(mape)
print('Accuracy:', round(accuracy, 2), '%.')


Model: 17.773574793782736, Actual: 16.465722631585038
Model: 10.610534465741145, Actual: 10.497081539108782
Model: 10.142353513934198, Actual: 9.639485549900499
Model: 42.057199053451214, Actual: 42.357748607195
Model: 18.83069312216966, Actual: 6.063413449065
Model: 30.43766802190331, Actual: 26.367723489059344
Model: 9.353473312659847, Actual: 7.934872992134268
Model: 42.60745680029219, Actual: 51.879055492810004
Model: 8.785371279257657, Actual: 7.861187715016644
Model: 13.118599509254926, Actual: 13.370124772445
Model: 21.430565696461034, Actual: 14.934077561135252
Model: 22.044781818731664, Actual: 20.180180267904998
Model: 14.954690891942958, Actual: 21.948365576357837
Model: 7.626130826484484, Actual: 5.702605711267501
Model: 14.758969222163055, Actual: 13.890200587874556
Model: 13.540244645514788, Actual: 15.198136307690001
Model: 11.44493389770377, Actual: 13.187881911505
Model: 23.724807733779066, Actual: 23.019568288954996
Model: 12.768805498242827, Actual: 12.05044388194499

ensemble learning

In [30]:
#bg = BaggingClassifier(DecisionTreeClassifier(), n_estimators = 1000)
#bg.fit(train_features, train_labels)
